### PR TITLE
Add new subscribe and help icons.

### PR DESCRIPTION
**Pull request by njostonehouse**

### CODE REVIEW

**Comment by njostonehouse** [comment]
@dbatiste Not sure, but do we want to change how we're compressing SVGs? Might be more efficient just to encode the actual markup.

**Comment by dbatiste** [comment]
[images-to-variables](https://github.com/Brightspace/images-to-variables) compresses both `png` and `svg`, and I've seen pretty significant compression in both cases.  Do you mean more efficient from a build perspective?

**Comment by njostonehouse** [comment]
No, I'm purely eyeballing the number of characters being stored in the `url` for these two cases, and having skimmed this article: https://css-tricks.com/probably-dont-base64-svg/.

**Comment by dlockhart** [comment]
Aside from how we store them, I would highly recommend [SVGOMG](https://jakearchibald.github.io/svgomg/). It uses [SVGO](https://github.com/svg/svgo) under the covers and achieves some awesome optimizing.

**Comment by njostonehouse** [comment]
imagemin (what images-to-variables uses) uses SVGO, so I bet we're good! Sorry guys :)

**Comment by dbatiste** [comment]
Yeah, I recall reading that article.  We don't base-64 encode the `svg`s, [just utf-8 encoding](https://github.com/Brightspace/images-to-variables/blob/master/lib/create.js#L58).  Currently we use [imagemin](https://www.npmjs.com/package/imagemin) for compression, and for `svg`, it uses [svgo](https://www.npmjs.com/package/svgo) as described in that article.

**Comment by dlockhart** [comment]
Neat!

**Comment by dbatiste** [comment]
Hmmm.  It looks like this component only uses images-to-variables for minifying.  This component does not use it to write out the variables (there's probably something slightly different that it outputs).  It looks like this component does base-64 encoding for all.  I think this should be updated similar to images-to-variables.

**Pull request merged**
