### PR TITLE
Add help and star (subscribe) icons as used in LP.

### PR DESCRIPTION
**Pull request by njostonehouse**

### CODE REVIEW

**Comment by njostonehouse** [comment]
@dlockhart @dbatiste I'm introducing a new branch here to create VUI icons as used in the pre-redesign monolith. Seem reasonable?

**Comment by dlockhart** [comment]
My only concern here is the "star" terminology and how it has the model built in. I'm assuming this icon is for "subscribe", so can we call it that instead? That would allow us to change the mental model (the star part) later if necessarily without making using it confusing. Also, should there be a corresponding "unsubscribe"?

**Comment by dlockhart** [comment]
I realize I'm being a bit of a hypocrite because I previously called the "settings" icon "sliders", which again hints at what the icon looks like, not what it does. Oops.

**Comment by njostonehouse** [comment]
I agree, but we already have "subscribe," and it looks different than what's currently used (grey star vs blue star). My intent is to merge them into a single icon (the redesigned "subscribe") in the main branch.

**Pull request closed without merging**
